name: crud_todo_app
description: Create a To-do List app managing CRUD in Firebase and Flutter

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: 3.35.6

dependencies:
  cloud_firestore: ^6.0.3
  context_menus: ^2.0.0+1
  dart_emoji: ^0.2.0+2
  equatable: ^2.0.7
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_slidable: ^4.0.3
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^3.1.0
  google_fonts: ^6.3.2
  hooks_riverpod: ^3.0.3
  intl: ^0.20.2
  json_annotation: ^4.9.0
  uuid: ^4.5.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  build_runner: ^2.7.1
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  integration_test:
    sdk: flutter
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  remove_from_coverage: ^2.0.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
